---
permalink: deploy/concept-virtual-storage-console-overview.html 
sidebar: sidebar 
keywords: overview, virtual, appliance, vsc, vasa, provider, sra, 
summary: Virtual Storage Console（VSC）、VASA Provider、Storage Replication Adapter（SRA）仮想アプライアンスは、ネットアップストレージシステムを使用するVMware環境の仮想マシンに対してエンドツーエンドのライフサイクル管理を提供します。管理者が vCenter Server 内でストレージを直接管理できるため、 VMware 環境のストレージとデータの管理が簡単になります。 
---
= VSC、VASA Provider、SRA仮想アプライアンスの概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Virtual Storage Console（VSC）、VASA Provider、Storage Replication Adapter（SRA）仮想アプライアンスは、ネットアップストレージシステムを使用するVMware環境の仮想マシンに対してエンドツーエンドのライフサイクル管理を提供します。管理者が vCenter Server 内でストレージを直接管理できるため、 VMware 環境のストレージとデータの管理が簡単になります。

VMware は vSphere 6.5 で vSphere Client という名前の新しい HTML5 ベースのクライアントを導入しました。VSC、VASA Provider、SRA仮想アプライアンス9.6では、vSphere Clientのみがサポートされます。VSC、VASA Provider、SRA仮想アプライアンスはvSphere Clientと統合されており、シングルサインオン（SSO）サービスを利用できます。複数の vCenter Server インスタンスがある環境では、管理する vCenter Server インスタンスごとに固有の VSC インスタンスを登録する必要があります。

VSC、VASA Provider、SRA仮想アプライアンスの各コンポーネントは、ストレージをより効率的に管理するための機能を提供します。



== Virtual Storage Console （ VSC ）

VSC では次の作業を実行できます。

* SRAとVASA Providerの両方で使用できるストレージコントローラをVSCに追加し、クレデンシャルを割り当て、ストレージコントローラのアクセス許可を設定する
* データストアをプロビジョニング
* vCenter Server 環境でデータストアと仮想マシンのパフォーマンスを監視します
* Role-Based Access Control （ RBAC ；ロールベースアクセス制御）を使用して、次の 2 つのレベルで vCenter Server オブジェクトへの管理者アクセスを制御します。
+
** 仮想マシンやデータストアなどの vSphere オブジェクト
+
これらのオブジェクトの管理には vCenter Server RBAC を使用します。

** ONTAP ストレージ
+
ストレージシステムの管理には ONTAP RBAC を使用します。



* ストレージに接続されているESXiホストのホスト設定を表示および更新します


NFS Plug-in for VMware vStorage APIs for Array Integration（VAAI）を使用することは、VSCのプロビジョニング処理にメリットがあります。NFS Plug-in for VAAI は、 ESXi ホストにインストールされている VMware の仮想ディスクライブラリを統合するソフトウェアライブラリです。VMware VAAI パッケージを使用すると、特定のタスクを物理ホストからストレージアレイにオフロードできます。シンプロビジョニングやハードウェアアクセラレーションなどのタスクをアレイレベルで実行して、 ESXi ホスト上のワークロードを削減できます。コピーオフロード機能やスペースリザベーション機能によって、 VSC の処理のパフォーマンスが向上します。

NetApp NFS Plug-in for VAAI は VSC に付属していません。ただし、プラグインのインストールパッケージをダウンロードして、からプラグインのインストール手順を確認できます。



== VASA Provider

VASA Provider for ONTAP は、 VMware vSphere APIs for Storage Awareness （ VASA ）を使用して、 VMware vSphere で使用されているストレージに関する情報を vCenter Server に送信します。VSC、VASA Provider、SRA仮想アプライアンスはVSCと統合されており、VASA Providerを使用して次のタスクを実行できます。

* VMware 仮想ボリューム（ vVol ）データストアをプロビジョニングする
* 環境に応じた異なるストレージのサービスレベル目標（ SLO ）を定義するストレージ機能プロファイルを作成して使用します
* データストアがストレージ機能プロファイルに準拠しているかどうかを確認する
* ボリュームやアグリゲートがしきい値に近づいたときに警告するようにアラームを設定します
* VVol データストアに作成された仮想マシンディスク（ VMDK ）と仮想マシンのパフォーマンスを監視する


ONTAP 9.6以前を使用している場合、VASA ProviderはVASA APIを使用してvCenter Serverと通信し、ZAPIと呼ばれるAPIを使用してONTAP と通信します。ONTAP 9.6以前のvVolダッシュボードを表示するためには、vCenter Serverをインストールして登録しておく必要があります。ONTAP 9.7を使用している場合、vVolダッシュボードを表示するためにVASA Providerに登録する必要はありません。

[NOTE]
====
ONTAP 9.6 以前では、 VASA Provider に専用の OnCommand API サービスインスタンスが必要です。OnCommand API サービスの 1 つのインスタンスを複数の VASA Provider インスタンスで共有することはできません。

====


== Storage Replication Adapter （ SRA ）

SRA を有効にして VMware Site Recovery Manager （ SRM ）と一緒に使用している場合、障害時に vCenter Server のデータストアと仮想マシンをリカバリできます。SRAを使用して、障害時のディザスタリカバリ用に、環境内の保護対象サイトとリカバリサイトを設定できます。

* 関連情報 *

https://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62040["ネットアップのマニュアル：OnCommand API Services"^]

http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=61278["ネットアップのマニュアル： NetApp NFS Plug-in for VMware VAAI"^]

https://mysupport.netapp.com/site/["ネットアップサポート"^]
