---
permalink: deploy/concept-guidelines-for-using-vsc-standard-roles.html 
sidebar: sidebar 
keywords: guidelines, using, VSC standard roles 
summary: Virtual Storage Console for VMware vSphereの標準ロールを使用するときは、一定のガイドラインに従う必要があります。 
---
= VSC の標準ロールの使用に関するガイドライン
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Virtual Storage Console for VMware vSphereの標準ロールを使用するときは、一定のガイドラインに従う必要があります。

標準ロールは直接変更しないでください。ロールを直接変更すると、 VSC をアップグレードするたびに変更が上書きされます。VSC をアップグレードするたびに、インストーラによって標準ロールの定義が更新されます。これにより、そのバージョンの VSC およびサポートされるすべてのバージョンの vCenter Server でロールを最新の状態に維持できます。

ただし、標準のロールを使用して環境に合わせたロールを作成することもできます。これを行うには、 VSC の標準ロールをコピーし、コピーしたロールを編集します。新しいロールを作成しても、 VSC Windows サービスを再起動またはアップグレードしてもこのロールを維持できます。

VSC の標準ロールの用途としては、次のようなものがあります。

* すべての VSC タスクに標準の VSC ロールを使用する。
+
このシナリオでは、標準ロールは VSC タスクの実行に必要なすべての権限をユーザに提供します。

* 複数のロールを組み合わせてユーザが実行できるタスクを拡張する。
+
単独では要件に合う標準の VSC ロールがない場合は、複数のロールを含む上位グループを作成してロールを拡張できます。

+
ユーザが vCenter Server 標準の別の権限を必要とする VSC 以外のタスクも実行する必要がある場合は、それらの権限を提供するロールを作成し、グループに追加します。

* より細分化されたロールを作成します。
+
標準の VSC ロールよりも少ない権限のロールが必要な場合は、 VSC ロールを使用して新しいロールを作成することができます。

+
この場合は、必要な VSC ロールのクローンを作成し、そのクローンを編集してユーザに必要な権限だけを残します。


