---
permalink: deploy/concept-configure-your-storage-system-environment.html 
sidebar: sidebar 
keywords: configuring, virtual, storage, console, vmware, vsphere, storage, system, environment, 
summary: Virtual Storage Console for VMware vSphereを使用すると、ストレージシステムの検出とストレージクレデンシャルの設定を単一のメカニズムで実行できます。クレデンシャルに基づいて、 Virtual Storage Console （ VSC ）ユーザがストレージシステムを使用してタスクを実行するために必要な ONTAP アクセス許可が付与されます。 
---
= Virtual Storage Console for VMware vSphereストレージシステム環境を設定します
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Virtual Storage Console for VMware vSphereを使用すると、ストレージシステムの検出とストレージクレデンシャルの設定を単一のメカニズムで実行できます。クレデンシャルに基づいて、 Virtual Storage Console （ VSC ）ユーザがストレージシステムを使用してタスクを実行するために必要な ONTAP アクセス許可が付与されます。

VSC でストレージリソースを表示して管理するには、まずストレージシステムを検出しなければなりません。検出プロセスでは、ストレージシステムの ONTAP クレデンシャルが必要になります。これはユーザ名とパスワードのペアに関連付けられた権限（ロール）で、ストレージシステムごとに割り当てられます。これらのユーザ名とパスワードのペアは、 ONTAP RBAC を使用するため、 ONTAP で設定する必要があります。これらのクレデンシャルを VSC で変更することはできません。を使用して、ONTAP RBACロールを定義できます。

[NOTE]
====
管理者としてログインすると、そのストレージシステムに対するすべての権限が自動的に付与されます。

====
VSC にストレージシステムを追加するときは、ストレージシステムの IP アドレス、およびそのシステムに関連付けられているユーザ名とパスワードのペアを入力する必要があります。VSC がストレージシステムの検出プロセスで使用するデフォルトクレデンシャルを設定することも、ストレージシステムが検出されたときにクレデンシャルを手動で入力することもできます。VSC に追加されるストレージシステムの詳細は、導入環境で有効にする拡張機能に自動的にプッシュされます。VASA Provider と Storage Replication Adapter （ SRA ）にストレージを手動で追加する必要はありません。VSCとSRAは、クラスタレベルおよびレベルでクレデンシャルの追加をサポートします。VASA Provider は、ストレージシステムを追加するためのクラスタレベルのクレデンシャルのみをサポートします。

環境に複数の vCenter Server インスタンスが含まれている場合、ストレージシステムページから VSC にストレージシステムを追加するときに、ストレージシステムを追加する vCenter Server ボックスが表示されます。このボックスで、ストレージシステムを追加する vCenter Server インスタンスを指定できます。データセンター名を右クリックしてストレージシステムを追加する場合は、そのデータセンターにサーバがすでに関連付けられているため、 vCenter Server インスタンスを指定するオプションは表示されません。

検出は、次のいずれかの方法で実行されます。いずれの場合も、新たに検出されるすべてのストレージシステムのクレデンシャルを指定する必要があります。

* VSC サービスが開始されると、 VSC の自動バックグラウンド検出プロセスが開始されます。
* ストレージシステムページまたはホスト/データセンターですべて再検出*ボタンをクリックすると、*アクション*メニュー（メニュー：アクション[ NetApp VSC >ホストおよびストレージデータの更新]）からこのボタンを選択できます。概要セクションの [ はじめに ] タブで * 発見 * をクリックすることもできます。


VSC の機能を使用してタスクを実行するときは、いずれも特定の権限が必要です。ユーザが実行できる操作は、 ONTAP ロールに関連付けられたクレデンシャルに基づいて制限できます。ストレージシステムのユーザ名とパスワードのペアを同じにすれば、複数のユーザで同じストレージシステムのクレデンシャルを共有し、同じ処理を実行することができます。
