---
permalink: deploy/task-set-default-credentials-for-storage-systems.html 
sidebar: sidebar 
keywords: setting, default, credentials, storage, systems, 
summary: Virtual Storage Console for VMware vSphereを使用して、vCenter Serverでストレージシステムのデフォルトクレデンシャルを設定できます。 
---
= ストレージシステムのデフォルトクレデンシャルを設定
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Virtual Storage Console for VMware vSphereを使用して、vCenter Serverでストレージシステムのデフォルトクレデンシャルを設定できます。

デフォルトクレデンシャルの作成に使用する vCenter Server を選択しておく必要があります。

ストレージシステムのデフォルトクレデンシャルを設定すると、（VSC）ではそれらのクレデンシャルを使用して、VSCが検出したストレージシステムにログインします。デフォルトクレデンシャルでログインできない場合は、ストレージシステムに手動でログインする必要があります。VSCとSRAは、クラスタレベルまたはレベルでストレージシステムのクレデンシャルの追加をサポートします。ただし、 VASA Provider はクラスタレベルのクレデンシャルとのみ連携します。

.手順
. VSC * Home *ページで、メニュー：設定[管理設定>ストレージシステムのデフォルトクレデンシャルの設定]をクリックします。
. ストレージ・システムのデフォルト・クレデンシャル*ダイアログ・ボックスで、ストレージ・システムのユーザ名とパスワードを入力します。
+
ストレージコントローラのクレデンシャルは、ユーザ名とパスワードのペアに基づいて ONTAP で割り当てられます。ストレージコントローラのクレデンシャルは、管理者アカウントまたはロールベースアクセス制御（ RBAC ）を使用するカスタムアカウントのどちらかです。

+
ストレージコントローラのユーザ名とパスワードのペアに関連付けられているロールを VSC で変更することはできません。VSC、VASA Provider、SRA仮想アプライアンスで使用する新しいONTAP ユーザロールを変更または作成するには、System Managerを使用します。

+
『Virtual Storage Console、VASA Provider、and Storage Replication Adapter for VMware®vSphere Deployment and Setup Guide for 9.7 Release]の「Configuring user roles and privileges」の項を参照してください。

. OK * をクリックして、デフォルトクレデンシャルを保存します。


ストレージ・システムのステータスが「認証エラー」と報告されたためにストレージ・システムのクレデンシャルを更新した場合は、 [ ストレージ・システム ] ページで [ すべて再検出 ] オプションをクリックする必要があります。これにより、新しいクレデンシャルを使用してストレージシステムへの接続が試行されます。
