---
permalink: deploy/task-discover-storage-systems-and-hosts.html 
sidebar: sidebar 
keywords: discovering, storage, systems, hosts, 
summary: vSphere Clientで（VSC）を初めて実行すると、ESXiホスト、そのLUNとNFSエクスポート、およびLUNとエクスポートを所有するネットアップストレージシステムがVSCによって検出されます。 
---
= ストレージシステムとホストを検出
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
vSphere Clientで（VSC）を初めて実行すると、ESXiホスト、そのLUNとNFSエクスポート、およびLUNとエクスポートを所有するネットアップストレージシステムがVSCによって検出されます。

.作業を開始する前に
* すべての ESXi ホストの電源をオンにして接続しておく必要があります。
* 検出するすべてのが実行されている必要があります。また、使用中のストレージプロトコル（NFS、iSCSI、またはFC）用のデータLIFが各クラスタノードに少なくとも1つ設定されている必要があります。


新しいストレージシステムの検出や既存のストレージシステムの情報の更新はいつでも実行でき、容量や設定に関する最新の情報を確認することができます。VSC でストレージシステムへのログインに使用されるクレデンシャルを変更することもできます。

ストレージシステムの検出時に、 vCenter Server インスタンスで管理している ESXi ホストから情報が収集されます。

.手順
. vSphere Client * Home *ページで、* Hosts and Clusters *を選択します。
. 必要なデータセンターを右クリックし、メニューを選択します。NetApp VSC [ホストおよびストレージデータの更新]。
+
この処理に時間がかかることを通知する確認ダイアログボックスが表示されます。

. [OK] をクリックします。
. ステータスが「認証エラー」の検出されたストレージコントローラを選択し、メニューからアクション[Modify]をクリックします。
. [ストレージ・システムの変更]ダイアログ・ボックスに必要な情報を入力します
. ステータスが「認証エラー」のすべてのストレージコントローラについて、手順 4 と 5 を繰り返します。


検出プロセスが完了したら、次の手順を実行します。

* VSCを使用して、* Adapter Settings *列、* MPIO Settings *列、または* NFS Settings *列にAlertアイコンが表示されるホスト用のESXiホスト設定を構成します。
* ストレージシステムのクレデンシャルを入力します。

