---
permalink: manage/concept-what-storage-capabilities-are.html 
sidebar: sidebar 
keywords: storage, capability, profiles, 
summary: ストレージ機能はストレージシステムの一連の属性であり、そのストレージ機能が関連付けられているストレージオブジェクトのストレージパフォーマンスのレベル、ストレージ効率、その他の機能（暗号化など）を特定します。 
---
= ストレージ機能について説明します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージ機能はストレージシステムの一連の属性であり、そのストレージ機能が関連付けられているストレージオブジェクトのストレージパフォーマンスのレベル、ストレージ効率、その他の機能（暗号化など）を特定します。

従来のデータストアの場合、ストレージ機能プロファイルを使用して共通の属性を持つ一貫性のあるデータストアを作成し、 QoS ポリシーを割り当てることができます。プロビジョニング時には、ストレージ機能プロファイルに一致するクラスタ、 SVM 、およびアグリゲートが表示されます。既存の従来のデータストアからストレージ機能プロファイルを生成するには、*ストレージマッピング*メニューの*グローバル自動生成プロファイル*オプションを使用します。プロファイルを作成したら、 VSC を使用してデータストアがプロファイルに準拠しているかどうかを監視できます。

VVolデータストアの場合、プロビジョニングウィザードでは、複数のストレージ機能プロファイルを使用してデータストア内に異なるFlexVol を作成できます。VMストレージポリシーを使用すると、その定義に従って、該当するFlexVol に仮想マシン用のVVolを自動的に作成できます。たとえば、代表的なストレージクラス（パフォーマンス制限や暗号化や FabricPool などの機能）用のプロファイルを作成することができます。あとで、仮想マシンのビジネスクラスを表す VM ストレージポリシーを vCenter Server に作成し、該当するストレージ機能プロファイルに名前（ Production 、 Test 、 HR など）でリンクできます。

VVolで使用する場合は、ストレージ機能プロファイルによって個々の仮想マシンのストレージパフォーマンスも設定され、パフォーマンス要件を最も満たすVVolデータストアのFlexVol に仮想マシンが配置されます。QoS ポリシーにパフォーマンスの最小 IOPS または最大 IOPS を指定できます。仮想マシンを最初にプロビジョニングするときはデフォルトのポリシーを使用できます。また、ビジネス要件の変化に応じてあとから VM ストレージポリシーを変更することもできます。

vCenter Server は LUN またはボリュームのストレージ機能を、その LUN またはボリュームでプロビジョニングされるデータストアに関連付けます。これにより、仮想マシンのストレージプロファイルに一致するデータストアに仮想マシンをプロビジョニングして、データストアクラスタ内のすべてのデータストアのストレージサービスレベルを同じにすることができます。

Virtual Storage Console（VSC）、VASA Provider、Storage Replication Adapter（SRA）仮想アプライアンスでは、新しいストレージ機能プロファイルを使用して各仮想ボリューム（VVOL）データストアを設定できます。これにより、同じVVOLデータストアにIOPS要件が異なる仮想マシンをプロビジョニングすることができます。IOPSの要件があるVMのプロビジョニングワークフローを実行する際には、互換性があるデータストアのリストにすべてのVVOLデータストアが表示されます。

[NOTE]
====
6.5より前のvCenter Server用の仮想マシンをプロビジョニングまたは変更しようとすると、互換性があるデータストアのリストには、パフォーマンスが「MAX_IOPS」に設定されたストレージ機能プロファイルを含むVVolデータストアのみが表示されます。それ以外のVVolデータストアは、互換性がないデータストアのリストに表示されます。これは無視してかまわず、互換性がないデータストアのリストからVVolデータストアを選択して仮想マシンをプロビジョニングまたは変更できます。

====