---
permalink: manage/concept-configure-vvols-datastores.html 
sidebar: sidebar 
keywords: configuring, vvols, datastores, virtual, volumes 
summary: VASA Provider for ONTAP を使用して、 VMware 仮想ボリューム（ vVol ）を作成および管理することができます。VVOL データストアをプロビジョニング、編集、マウント、削除できます。また、 VVOL データストアへのストレージの追加や VVOL データストアからのストレージの削除も行うことができます。柔軟性を高めることができます。すべての仮想マシンおよび関連する VMDK をプロビジョニングおよび管理できます。 
---
= vVolデータストアを設定する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VASA Provider for ONTAP を使用して、 VMware 仮想ボリューム（ vVol ）を作成および管理することができます。VVOL データストアをプロビジョニング、編集、マウント、削除できます。また、 VVOL データストアへのストレージの追加や VVOL データストアからのストレージの削除も行うことができます。柔軟性を高めることができます。すべての仮想マシンおよび関連する VMDK をプロビジョニングおよび管理できます。

VVOL データストアは、ストレージコンテナ（「バッキングストレージ」とも呼ばれます）に含まれる 1 つ以上の FlexVol ボリュームで構成されます。仮想マシンは 1 つの vVol データストアまたは複数の vVol データストアに分散している場合があります。

複数の FlexVol を含む VVOL データストアを作成する場合は、ストレージコンテナ内のすべての FlexVol で同じプロトコル（ NFS 、 iSCSI 、または FCP ）および同じ Storage Virtual Machine （ SVM ）を使用する必要があります。

基盤となるストレージについての詳しい情報は必要ありません。たとえば、ストレージを格納する FlexVol を特定する必要はありません。FlexVol をVVOLデータストアに追加すると、ストレージ要件がストレージコンテナで管理されるようになり、VMのプロビジョニング時に、容量のないバッキングボリュームにVMがプロビジョニングされる状態を防ぐことができます。

[NOTE]
====
パフォーマンスと柔軟性を高めるために、 1 つの vVol データストアに複数の FlexVol を含めることを推奨します。FlexVol ボリュームの LUN 数には制限があり、それによって仮想マシンの数が制限されるため、複数の FlexVol を使用することで、より多くの仮想マシンを vVol データストアに格納することができます。

====
セットアッププロセスでは、作成する vVol データストアのストレージ機能プロファイルを指定する必要があります。1 つの vVol データストアに対して 1 つ以上の VASA Provider のストレージ機能プロファイルを選択できます。また、ストレージコンテナ内に自動で作成される vVol データストアに適用するデフォルトのストレージ機能プロファイルも指定できます。

VASA Provider では、仮想マシンのプロビジョニングまたは VMDK の作成時に、必要に応じてさまざまなタイプの VVOL を作成します。

* * 設定 *
+
この vVol データストアは、設定情報を格納するために VMware vSphere で使用されます。

+
SAN （ブロック）環境の場合、ストレージは 4GB の LUN です。

+
NFS 実装の場合は、 vmx ファイルなどの VM 構成ファイル、および他の VVOL データストアへのポインタを含むディレクトリになります。

* * データ *
+
この vVol には、オペレーティングシステムの情報やユーザファイルが格納されます。

+
SAN 環境の場合は、仮想ディスクと同じサイズの LUN です。

+
NFS 環境の場合は、仮想ディスクと同じサイズのファイルです。

* * スワップ *
+
この vVol は、仮想マシンの電源をオンにすると作成され、オフにすると削除されます。

+
SAN 環境の場合は、仮想メモリと同じサイズの LUN です。

+
NFS 環境の場合は、仮想メモリと同じサイズのファイルです。

* * メモリ *
+
この vVol は、 VM スナップショットの作成時にメモリのスナップショットオプションを選択した場合に作成されます。

+
SAN 環境の場合は、仮想メモリと同じサイズの LUN です。

+
NFS 環境の場合は、仮想メモリと同じサイズのファイルです。


