---
permalink: manage/concept-datastore-reports.html 
sidebar: sidebar 
keywords: datastore, reports, 
summary: データストアレポートには、従来のデータストアと、これらのデータストアに作成された仮想マシンに関する詳細情報が表示されます。 
---
= データストアレポート
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
データストアレポートには、従来のデータストアと、これらのデータストアに作成された仮想マシンに関する詳細情報が表示されます。

従来のダッシュボードを使用すると、 vCenter Server 内のデータストアおよび仮想マシンの潜在的な問題を確認して特定できます。レポートの表示、ソート、エクスポートが可能です。従来のデータストアおよび仮想マシンのレポートデータは、 vCenter Server から提供されます。

データストアには、次のレポートがあらかじめ定義されています。

* データストアレポート
* 仮想マシンレポート




== データストアレポート

Datastore Report メニューには、データストアに関する次のパラメータの情報が表示されます。

* データストアの名前
* データストアのタイプ： NFS または VMFS
* 空きスペース
* 使用済みスペース
* 合計スペース
* 使用済みスペースの割合
* 使用可能なスペースの割合
* IOPS
+
データストアの IOPS が表示されます。

* レイテンシ
+
データストアのレイテンシ情報が表示されます。



レポートが生成された時刻を確認することもできます。[ データストアレポート ] メニューでは、要件に応じてレポートを整理し、 [*CSV にエクスポート ] ボタンを使用して整理されたレポートをエクスポートできます。レポート内のデータストア名は、選択したデータストアの Monitor タブに移動するためのリンクで、データストアのパフォーマンス指標を確認できます。



== 仮想マシンレポート

Virtual Machine Reportメニューでは、選択したvCenter Serverに対してVSCでプロビジョニングされたデータストアを使用するすべての仮想マシンについて、次のパフォーマンス指標が表示されます。

* 仮想マシンの名前
* コミット済み容量
+
仮想マシンのコミット済み容量の値が表示されます。

* アップタイム
+
仮想マシンの電源がオンになり、 ESXi ホストで利用可能になってからの時間が表示されます。

* レイテンシ
+
仮想マシンに関連付けられているすべてのデータストアでの仮想マシンのレイテンシが表示されます。

* 電源状態
+
仮想マシンの電源がオンになっているかオフになっているかが表示されます。

* ホスト
+
仮想マシンを使用できるホストシステムが表示されます。



レポート内の各仮想マシン名は、選択した仮想マシンの [ モニタ ] タブへのリンクです。仮想マシンのレポートを要件に応じてソートし、レポートを「.csv」ファイルでエクスポートして、ローカルシステムに保存できます。保存したレポートには、レポートのタイムスタンプも追加されます。
