---
permalink: manage/reference-considerations-for-migrating-virtual-machines.html 
sidebar: sidebar 
keywords: considerations, for, migrating, or, cloning, virtual, machines, 
summary: データセンター内の既存の仮想マシンを移行する場合の考慮事項について理解しておく必要があります。 
---
= 仮想マシンの移行またはクローニングに関する考慮事項
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
データセンター内の既存の仮想マシンを移行する場合の考慮事項について理解しておく必要があります。



== 保護された仮想マシンを移行します

保護された仮想マシンは次の場所に移行できます。

* 別の ESXi ホストにある同じ VVOL データストア
* 同じ ESXi ホスト上に互換性のある異なる VVOL データストアがあります
* 互換性がある異なる VVOL データストアが別の ESXi ホストにあります


仮想マシンを別の FlexVol に移行すると、それぞれのメタデータファイルに仮想マシン情報も反映されます。仮想マシンを同じストレージを持つ別のESXiホストに移行した場合、基盤となるFlexVol ボリュームmetadafileは変更されません。



== 保護された仮想マシンのクローン作成

保護された仮想マシンは、次の場所にクローニングできます。

* レプリケーショングループを使用して同じ FlexVol ボリュームの同じコンテナ
+
同じ FlexVol ボリュームのメタデータファイルが、クローニングされた仮想マシンの詳細で更新されます。

* レプリケーショングループを使用して、異なる FlexVol の同じコンテナ
+
クローニングされた仮想マシンが配置された FlexVol ボリュームでは、クローニングされた仮想マシンの詳細がメタデータファイルに反映されます。

* 別のコンテナまたは vVol データストアです
+
クローニングされた仮想マシンが配置された FlexVol ボリュームでは、メタデータファイルに仮想マシンの詳細が更新されます。



VMware では、現在、仮想マシンを仮想マシンテンプレートにクローニングすることはできません。

保護された仮想マシンのクローン作成がサポートされています。



== 仮想マシンのスナップショット

現在、メモリのない仮想マシンのスナップショットのみがサポートされています。仮想マシンにメモリ付きの Snapshot がある場合、その仮想マシンは保護対象とはみなされません。

メモリ Snapshot を持つ保護されていない仮想マシンを保護することもできません。このリリースでは、仮想マシンの保護を有効にする前にメモリスナップショットを削除する必要があります。
