---
permalink: manage/task-provision-datastores.html 
sidebar: sidebar 
keywords: provisioning, datastores, 
summary: データストアをプロビジョニングすると、仮想マシンとその仮想マシンディスク（ VMDK ）用の論理コンテナが作成されます。データストアをプロビジョニングし、 1 台のホスト、クラスタ内のすべてのホスト、またはデータセンター内のすべてのホストに接続できます。 
---
= データストアをプロビジョニング
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
データストアをプロビジョニングすると、仮想マシンとその仮想マシンディスク（ VMDK ）用の論理コンテナが作成されます。データストアをプロビジョニングし、 1 台のホスト、クラスタ内のすべてのホスト、またはデータセンター内のすべてのホストに接続できます。

.作業を開始する前に
* Virtual Storage Console （ VSC ）に直接接続された SVM にデータストアをプロビジョニングする場合は、デフォルトの vsadmin ユーザアカウントまたは vsadmin ロールではなく、適切な権限を持つユーザアカウントを使用して SVM を VSC に追加しておく必要があります。
+
クラスタを追加してデータストアをプロビジョニングすることもできます。

* ESXiホストの接続先のすべてのネットワークのサブネットの詳細が「kaminoprefs.xml」に入力されていることを確認する必要があります。
+
VSC 9.6導入およびセットアップガイドの「異なるサブネット間でのデータストアのマウントの有効化」のセクションを参照してください。

* NFSまたはiSCSIを使用していて、ESXiホストとストレージシステムでサブネットが異なる場合は、「kaminoprefs」プリファレンスファイルのNFSまたはiSCSI設定にESXiホストのサブネットマスクを含める必要があります。
+
このプリファレンスファイルはVVolデータストアの作成時にも当てはまります。プリファレンスファイルの詳細および異なるサブネット間でのデータストアのマウントの有効化については、Virtual Storage Console、VASA Provider、Storage Replication Adapter 9.6導入およびセットアップガイドを参照してください。

* VASA Provider が有効な状態で、 NFS データストアまたは VMFS データストアのストレージ機能プロファイルを指定する場合は、 1 つ以上のストレージ機能プロファイルを作成しておく必要があります。
* NFSv4.1 データストアを作成する場合は、 SVM レベルで NFSv4.1 を有効にしておく必要があります。


* Provision Datastore * オプションを使用すると、データストアのストレージ機能プロファイルを指定できます。ストレージ機能プロファイルを使用すると、一貫した Service Level Objectives （ SLO ；サービスレベル目標）を確保し、プロビジョニングプロセスを簡易化できます。ストレージ機能プロファイルは VASA Provider が有効な場合にのみ指定できます。VSC、VASA Provider、SRA仮想アプライアンスでは、次のプロトコルがサポートされます。

* NFSv3 および NFSv4.1
* VMFS5 および VMFS6


データストアは、 NFS ボリュームまたは LUN 上に作成されます。

* NFS データストアの場合、ストレージシステム上に NFS ボリュームが作成され、エクスポートポリシーが更新されます。
* VMFS データストアの場合、新しいボリュームが作成され（既存のボリュームの使用を選択した場合は既存のボリュームが使用される）、 LUN および igroup が作成されます。


[NOTE]
====
VMware では、データストアクラスタに対して NFSv4.1 がサポートされません。

====
プロビジョニング時にストレージ機能プロファイルを指定しなかった場合は、あとでストレージマッピングページを使用してデータストアをストレージ機能プロファイルにマッピングできます。

.手順
. データストアプロビジョニングウィザードには次のいずれかからアクセスできます。
+
[cols="1a,1a"]
|===
| アクセスを開始するページ | 実行する手順 


 a| 
* vSphere Clientのホームページ*
 a| 
.. [*Hosts and Clusters*] をクリックします。
.. ナビゲーションペインで、データストアをプロビジョニングするデータセンターを選択します。
.. データストアをマウントするホストを指定するには、次の手順を参照してください。




 a| 
* Virtual Storage Consoleのホームページ*
 a| 
.. [* 概要 *] をクリックします。
.. [* はじめに * ] タブをクリックします。
.. [* Provision （プロビジョン） ] ボタンをクリックします
.. Browse （参照） * をクリックして、次の手順に従ってデータストアをプロビジョニングするデスティネーションを選択します。


|===
. データストアのマウント先のホストを指定します。
+
[cols="1a,1a"]
|===
| データストアを利用できるようにするホスト | 手順 


 a| 
データセンター内のすべてのホスト
 a| 
データセンターを右クリックして、メニューから「NetApp VSC [Provision Datastore]」を選択します。



 a| 
クラスタ内のすべてのホスト
 a| 
ホストクラスタを右クリックして、メニューから「NetApp VSC [Provision Datastore]」を選択します。



 a| 
単一のホスト
 a| 
ホストを右クリックして、メニューを選択します。NetApp VSC [Provision Datastore]。

|===
. データストアを作成するには、* New Datastore *ダイアログボックスのフィールドに値を入力します。
+
ダイアログボックス内のフィールドのほとんどはわかりやすいもので、説明を必要としません。以下は、説明が必要な一部のフィールドのリストです。

+
[cols="1a,1a"]
|===
| セクション | 説明 


 a| 
全般
 a| 
New Datastore Provisioning *ダイアログボックスの* General *セクションには、新しいデータストアのデスティネーション、名前、サイズ、タイプ、およびプロトコルを入力するオプションがあります。NFS * または * VMFS * プロトコルを選択すると、従来のデータストアを設定できます。VVolデータストアの設定にはVVolデータストアタイプを使用します。VASA Provider が有効になっている場合は、ストレージ機能プロファイルを使用するかどうかも指定できます。* Datastore cluster * オプションは、従来のデータストアに対してのみ使用できます。「 * Advanced * 」オプションを使用して、 * VMFS5 * または * VMFS6 * ファイルシステムを指定する必要があります。



 a| 
ストレージシステム
 a| 
「一般」セクションでオプションを選択した場合は、リストされているストレージ機能プロファイルのいずれかを選択できます。ストレージシステムと Storage Virtual Machine に対する推奨設定があらかじめ選択されています。ただし、必要に応じて値を変更できます。



 a| 
ストレージ属性
 a| 
アグリゲート * オプションとボリューム * オプションには、デフォルトで推奨値が設定されます。これらの値は要件に応じてカスタマイズが可能です。「 * 詳細設定 * 」メニューの「 * スペースリザーブ * 」オプションにも最適な結果が得られます。



 a| 
まとめ
 a| 
新しいデータストアについて指定したパラメータの概要を確認できます。

|===
. 「*概要*」セクションで、「*完了*」をクリックします。

