---
permalink: manage/task-provision-vvol-datastores.html 
sidebar: sidebar 
keywords: provisioning, vvols, datastores, 
summary: データストアのプロビジョニングウィザードを使用してVVOLデータストアをプロビジョニングできるのは、VSC、VASA Provider、SRA仮想アプライアンスでVASA Providerが有効になっている場合のみです。 
---
= vVol データストアをプロビジョニングする
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
vVolデータストアのプロビジョニングは、仮想アプライアンスでVASA Providerが有効になっているVSC、VASA Provider、SRAが有効になっている場合にのみ、*のデータストアのプロビジョニングウィザードを使用して実行できます。

.作業を開始する前に
* ESXiホストの接続先のすべてのネットワークのサブネットの詳細が'kaminoprefs.xmlに入力されていることを確認する必要があります
+
VSC 9.7導入およびセットアップガイドの「異なるサブネット間でのデータストアのマウントの有効化」のセクションを参照してください。

* 逆方向のレプリケーションが成功するように、ソースサイトとターゲットサイトの両方のデータストアで同様のレプリケーションポリシーとスケジュールを設定する必要があります。


.このタスクについて
*データストアのプロビジョニング*メニューでは、データストアのストレージ機能プロファイルを指定できます。これにより、一貫したサービスレベル目標（SLO）を指定し、プロビジョニングプロセスを簡易化できます。ストレージ機能プロファイルは VASA Provider が有効な場合にのみ指定できます。

バッキングストレージとして使用するFlexVol ボリュームは、ONTAP 9.5以降を実行している場合にのみvVolダッシュボードに表示されます。VVOLデータストアのプロビジョニングには、vCenter Server * New Datastore *ウィザードは使用しないでください。

* VVol データストアを作成するときは、クラスタのクレデンシャルを使用する必要があり
+
SVM のクレデンシャルを使用して vVol データストアを作成することはできません

* VASA Provider では、あるプロトコルを使用する VVol データストアでホストされている仮想マシンを別のプロトコルを使用するデータストアにクローニングすることはできません。
* ソースサイトとデスティネーションサイトの両方でクラスタのペアリングと SVM のペアリングを完了しておく必要があります。


.手順
. vSphere Client のホームページで、 * Hosts and Clusters * をクリックします。
. ナビゲーションペインで、データストアをプロビジョニングするデータセンターを選択します。
. データストアのマウント先のホストを指定します。
+
[cols="1a,1a"]
|===
| データストアを利用できるようにするホスト | 手順 


 a| 
データセンター内のすべてのホスト
 a| 
データセンターを右クリックして、メニューから「NetApp VSC [Provision Datastore]」を選択します。



 a| 
クラスタ内のすべてのホスト
 a| 
クラスタを右クリックして、メニューを選択します。NetApp VSC [Provision Datastore]。



 a| 
単一のホスト
 a| 
ホストを右クリックして、メニューを選択します。NetApp VSC [Provision Datastore]。

|===
. データストアを作成するには、* New Datastore *ダイアログボックスのフィールドに値を入力します。
+
ダイアログボックス内のフィールドのほとんどはわかりやすいもので、説明を必要としません。以下は、説明が必要な一部のフィールドのリストです。

+
[cols="1a,1a"]
|===
| セクション | 説明 


 a| 
全般
 a| 
New Datastore *ダイアログボックスの* General *セクションには、新しいデータストアの場所、名前、概要 、タイプ、およびプロトコルを入力するオプションがあります。vVol データストアの設定には vVol データストアタイプを使用します。

[NOTE]
====
VVOL レプリケーション用の iSCSI VVOL データストアをプロビジョニングする場合は、ターゲットサイトで VVOL データストアを作成する前に、 SnapMirror の更新とクラスタの再検出を実行する必要があります。

====


 a| 
ストレージシステム
 a| 
このセクションでは、 VVOL データストアでレプリケーションを有効にするか無効にするかを選択できます。このリリースでは、非同期タイプのレプリケーションプロファイルのみが許可されています。表示されたストレージ機能プロファイルを 1 つ以上選択できます。ペアリングされている * ストレージシステム * および * Storage VM * の推奨値が自動的に設定されます。推奨値は、 ONTAP でペアリングされている場合にのみ設定されます。これらの値は必要に応じて変更できます。

[NOTE]
====
ONTAP でFlexVol ボリュームを作成するときは、ストレージ機能プロファイルで選択する属性を使用してボリュームを作成する必要があります。読み取り / 書き込みの FlexVol ボリュームとデータ保護 LUN の属性は、どちらもほぼ同じでなければなりません。

====
FlexVol ボリュームを作成し、 ONTAP で SnapMirror を初期化したら、 VSC でストレージを再検出して新しいボリュームを認識できるようにする必要があります。



 a| 
ストレージ属性
 a| 
SnapMirror のスケジュールと、既存のリストから必要な FlexVol のスケジュールを選択します。このスケジュールは、 [VM ストレージポリシー ] ページで選択したスケジュールと同様のものにする必要があります。このユーザは、 SnapMirror を使用する ONTAP で、表示されている FlexVol ボリュームを作成しておく必要があります。VVol の作成に使用するデフォルトのストレージ機能プロファイルを選択するには、 * default storage capability profile * オプションを使用します。

|===
. 「*概要*」セクションで、「*完了*」をクリックします。
+
VVOL データストアの設定時にバックエンドでレプリケーショングループが作成されます。



* 関連情報 *

xref:reference-verify-vvol-dashboard-data-requirements.adoc[VVolダッシュボードのデータ要件]
